[sc115424] add send messages by batch to sqs sdk
agorapulse/micronaut-aws-sdk pull request #199
Opened 2023-12-04 15:04 UTC by mtakerrabet

add send messages by batch to to an aws sqs queue

2023-12-05 12:07 UTC, musketyr requested changes
looks good, just a minor thing: I think using the `messagesList` for a `Map` is not a good practice. can you rename it.

I think it would make sense to to also add the support into `@QueueClient` declarative clients. e.g. by using `@Batch` on a `Map<String, Object>` parameters, what do you think?

another subject is if there is a need to backport the change also into AWS SDK v1 library. so far we were trying to keep these in sync.

2023-12-05 12:07 UTC, musketyr commented on subprojects/micronaut-amazon-awssdk-sqs/src/main/java/com/agorapulse/micronaut/amazon/awssdk/sqs/groovy/SimpleQueueServiceExtensions.java
> +        Map<String, String> messagesList,
why is `messagesList` a map?

2023-12-05 12:07 UTC, musketyr commented on subprojects/micronaut-amazon-awssdk-sqs/src/main/java/com/agorapulse/micronaut/amazon/awssdk/sqs/groovy/SimpleQueueServiceExtensions.java
> +        Map<String, String> messagesList,
it's worth renaming `messages` or `messagesByIds`

2023-12-07 08:46 UTC, mtakerrabet commented
> looks good, just a minor thing: I think using the `messagesList` for a `Map` is not a good practice. can you rename it.
> 
> I think it would make sense to to also add the support into `@QueueClient` declarative clients. e.g. by using `@Batch` on a `Map<String, Object>` parameters, what do you think?
> 
> another subject is if there is a need to backport the change also into AWS SDK v1 library. so far we were trying to keep these in sync.

Hi @musketyr, thanks for the review, I renamed the parameter and did the modification for the `@QueueClient` declarative clients client, but I didn't the changes on the  AWS SDK v1 library, the `SendMessageBatchRequest` is provided by the `software.amazon.awssdk:sqs` which is not embedded in

2023-12-07 15:06 UTC, wmedjek approved these changes

2023-12-07 15:16 UTC, musketyr commented on subprojects/micronaut-amazon-awssdk-sqs/src/main/java/com/agorapulse/micronaut/amazon/awssdk/sqs/groovy/SimpleQueueServiceExtensions.java
> +        Map<String, String> messagesList,
thanks, I will take a look and made some tests

2023-12-07 16:52 UTC, musketyr commented
@mtakerrabet please, check this update to your PR: https://github.com/agorapulse/micronaut-aws-sdk/pull/199/commits/cd862c244f2a50c942182ceeeec39f64170132fd.

So the number of messages in the batch has its hard limit? In that case we can partition the messages directly in the introduced method.

2023-12-08 07:59 UTC, mtakerrabet commented
> @mtakerrabet please, check this update to your PR: [cd862c2](https://github.com/agorapulse/micronaut-aws-sdk/commit/cd862c244f2a50c942182ceeeec39f64170132fd).
> 
> So the number of messages in the batch has its hard limit? In that case we can partition the messages directly in the introduced method.

Thank you for the updates @musketyr, it looks good to me, 
and for the number of messages in the batch, yes, sqs set a hard limit to 10 messages by request

2024-02-16 13:46 UTC, closed without merging