[sc130691] add a function to micronaut-aws-sdk dynamo lib to update multiple attributes
agorapulse/micronaut-aws-sdk pull request #236
Opened 2024-06-05 15:18 UTC by mkoterba-agorapulse

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19VzuxXDRITx3UDdyD60sHIMxQRpM5mk8g%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=i7T73xa)

# Summary

add a function to micronaut-aws-sdk dynamo lib to update multiple attributes

2024-06-06 09:36 UTC, musketyr requested changes
Looks good. Please, check the comment add also fix the CodeNarc violations. you can see them locally by running `./gradlew aggregateCodeNarc`. you can use `@SuppressWarnings('NoJavaUtilDate')` to get rid of that particular violation.
Also be aware this change is only for AWS SDK v1, there is some more advanced way how to update entities in v2 integration.

https://github.com/agorapulse/micronaut-aws-sdk/blob/9cb63e8b7af6a41ebd183c7fc84e714f5ba35a8b/subprojects/micronaut-amazon-awssdk-dynamodb/src/main/java/com/agorapulse/micronaut/amazon/awssdk/dynamodb/DynamoDbService.java#L110-L130

<img width="1250" alt="Snímek obrazovky 2024-06-06 v 11 27 20" src="https://github.com/agorapulse/micronaut-aws-sdk/assets/660405/2c4ae56c-127f-40d1-8cb3-46c6fd895b1b">

2024-06-06 09:36 UTC, musketyr commented on subprojects/micronaut-aws-sdk-dynamodb/src/test/groovy/com/agorapulse/micronaut/aws/dynamodb/DefaultDynamoDBServiceSpec.groovy
> +import static com.agorapulse.micronaut.aws.dynamodb.builder.Builders.*
we need to keep this unchanged because of the generated docs

2024-06-14 16:52 UTC, mkoterba-agorapulse commented on subprojects/micronaut-aws-sdk-dynamodb/src/test/groovy/com/agorapulse/micronaut/aws/dynamodb/DefaultDynamoDBServiceSpec.groovy
> +import static com.agorapulse.micronaut.aws.dynamodb.builder.Builders.*
done

2024-06-14 16:53 UTC, mkoterba-agorapulse commented
CodeNarc issues fixed

2024-07-10 08:21 UTC, musketyr approved these changes

2024-07-10 08:21 UTC, merged