[Ch48889] support for java.time.Instant in DynamoDBService methods added
agorapulse/micronaut-aws-sdk pull request #83
Opened 2021-07-06 10:54 UTC by wololock

This pull request adds the following method variants to the `DynamoDBService`:

* `countByDates(Object hashKey, String rangeKeyName, Instant after, Instant before, Instant maxAfterDate)`
* `countByDates(Object hashKey, String rangeKeyName, Instant after, Instant before)`
* `queryByDates(Object hashKey, String rangeKeyName, Instant after, Instant before, Instant maxAfterDate)`
* `queryByDates(Object hashKey, String rangeKeyName, Instant after, Instant before)`

2021-07-06 18:34 UTC, musketyr commented
looks good to me but there are also methods which uses `Date` secretly within a `Map`. I'm not sure if they can be replaced with the new methods you have added or you need to add support for `Instants` into this methods. maybe you can just check the type of the values in the map. I've added @descorps to check if the new methods are sufficient for his migration.

2021-07-07 07:55 UTC, wololock commented
@musketyr, you're comment is accurate, and I already took this internal `Map` into account in the recommended implementation :) All `byDates` methods use map to pass all dates, and conversion from `java.uti.Date` and `java.time.Instant` is done by the dedicated `DefaultDynamoDBService.serializeDate(date)` method. I overloaded it with the `java.time.Instant` parameter type, so both types can be serialized to the string date format correctly.

I wondered, however, if it works fine when used in pure Java. Spock tests with Groovy worked as expected, so I also updated Java's `DynamoDBServiceTest` JUnit test to use `java.time.Instant` variant too - all works fine.

2021-07-12 05:51 UTC, musketyr requested changes
I'm fighting with the test coverage reports right now but I believe the new `serializeDate` method is never used because of missing branch in `buildAttributeValue` method- string conversion is used instead which works well.

you should either add the branch into that method or remove the new `serializeDate` method to ensure misunderstanding in a future

https://github.com/agorapulse/micronaut-aws-sdk/pull/83/files#diff-8964103e91471c37de9c7e6e5e964d95f9f2e2cbeaf39182cc66eb6af5632895R673-R684

2021-07-12 06:40 UTC, musketyr approved these changes

2021-07-12 06:56 UTC, wololock commented
I double-checked, and the new `serializeDate` method was called with the `java.time.Instant` parameter. I put a breakpoint inside this method and then run the `DynamoDBServiceTest` (Java JUnit test) with the debugger - when the `java.time.Instant` parameter was used, this method was called.

Anyway, there is one thing that may be confusing. All `*ByDates` methods use this [`buildDateConditions` method](https://github.com/agorapulse/micronaut-aws-sdk/blob/532f7872d67e8803b602d35490358d13865434c3/subprojects/micronaut-aws-sdk-dynamodb/src/main/groovy/com/agorapulse/micronaut/aws/dynamodb/DefaultDynamoDBService.groovy#L709-L734). What might be confusing is the fact that this method expects `Map<String, Date>` map type. However, even statically compiled Java code accepts `java.time.Instant` values (I double-checked it with the debugger), most probably because of the dynamic nature and the fact, that the upper methods that call it, accept `Map` type without specifying the generics.

I added the branch in the method you suggested, just so the `java.time.Instant` type can be converted in any scenario. Now I can see in the IDE that the method is used - test coverage should be fine now.

2021-07-12 10:26 UTC, musketyr commented
Thanks for explanation!

2021-07-12 10:26 UTC, merged